import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1724212724084 implements MigrationInterface {
    name = 'Migration1724212724084'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "race" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "race" varchar NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "c_class" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "cclass" varchar NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer)`);
        await queryRunner.query(`CREATE TABLE "user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar NOT NULL, "phonenumber" varchar NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "temporary_character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer, CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f97ed21947c8cf384d1b845278" FOREIGN KEY ("cclassId") REFERENCES "c_class" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_04c2fb52adfa5265763de8c4464" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_character"("id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId") SELECT "id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId" FROM "character"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`ALTER TABLE "temporary_character" RENAME TO "character"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "character" RENAME TO "temporary_character"`);
        await queryRunner.query(`CREATE TABLE "character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer)`);
        await queryRunner.query(`INSERT INTO "character"("id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId") SELECT "id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId" FROM "temporary_character"`);
        await queryRunner.query(`DROP TABLE "temporary_character"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`DROP TABLE "c_class"`);
        await queryRunner.query(`DROP TABLE "race"`);
    }

}
