import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPlace1782837726476 implements MigrationInterface {
    name = 'AddPlace1782837726476'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "place" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "type" varchar NOT NULL, "grid_x" integer NOT NULL, "grid_y" integer NOT NULL, "width" integer NOT NULL DEFAULT (1), "height" integer NOT NULL DEFAULT (1))`);
        await queryRunner.query(`CREATE TABLE "temporary_character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer, "local_x" integer NOT NULL DEFAULT (0), "local_y" integer NOT NULL DEFAULT (0), "currentPlaceId" integer, CONSTRAINT "FK_04c2fb52adfa5265763de8c4464" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f97ed21947c8cf384d1b845278" FOREIGN KEY ("cclassId") REFERENCES "c_class" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_character"("id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId") SELECT "id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId" FROM "character"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`ALTER TABLE "temporary_character" RENAME TO "character"`);
        await queryRunner.query(`CREATE TABLE "temporary_character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer, "local_x" integer NOT NULL DEFAULT (0), "local_y" integer NOT NULL DEFAULT (0), "currentPlaceId" integer, CONSTRAINT "FK_04c2fb52adfa5265763de8c4464" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f97ed21947c8cf384d1b845278" FOREIGN KEY ("cclassId") REFERENCES "c_class" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_85fd0fc63059366ab437ab3a500" FOREIGN KEY ("currentPlaceId") REFERENCES "place" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_character"("id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId", "local_x", "local_y", "currentPlaceId") SELECT "id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId", "local_x", "local_y", "currentPlaceId" FROM "character"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`ALTER TABLE "temporary_character" RENAME TO "character"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "character" RENAME TO "temporary_character"`);
        await queryRunner.query(`CREATE TABLE "character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer, "local_x" integer NOT NULL DEFAULT (0), "local_y" integer NOT NULL DEFAULT (0), "currentPlaceId" integer, CONSTRAINT "FK_04c2fb52adfa5265763de8c4464" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f97ed21947c8cf384d1b845278" FOREIGN KEY ("cclassId") REFERENCES "c_class" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "character"("id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId", "local_x", "local_y", "currentPlaceId") SELECT "id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId", "local_x", "local_y", "currentPlaceId" FROM "temporary_character"`);
        await queryRunner.query(`DROP TABLE "temporary_character"`);
        await queryRunner.query(`ALTER TABLE "character" RENAME TO "temporary_character"`);
        await queryRunner.query(`CREATE TABLE "character" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "title" varchar NOT NULL, "appearance" varchar NOT NULL, "position_x" integer NOT NULL, "position_y" integer NOT NULL, "max_health" integer NOT NULL, "curr_health" integer NOT NULL, "max_energy" integer NOT NULL, "curr_energy" integer NOT NULL, "max_mana" integer NOT NULL, "curr_mana" integer NOT NULL, "max_spirit" integer NOT NULL, "curr_spirit" integer NOT NULL, "level" integer NOT NULL, "curr_xp" integer NOT NULL, "xp" integer NOT NULL, "strength" integer NOT NULL, "intelligence" integer NOT NULL, "dexterity" integer NOT NULL, "charisma" integer NOT NULL, "spirit" integer NOT NULL, "luck" integer NOT NULL, "talent" integer NOT NULL, "raceId" integer, "cclassId" integer, "userId" integer, CONSTRAINT "FK_04c2fb52adfa5265763de8c4464" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f97ed21947c8cf384d1b845278" FOREIGN KEY ("cclassId") REFERENCES "c_class" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a7485d062b19695002b6175e8fb" FOREIGN KEY ("raceId") REFERENCES "race" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "character"("id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId") SELECT "id", "name", "title", "appearance", "position_x", "position_y", "max_health", "curr_health", "max_energy", "curr_energy", "max_mana", "curr_mana", "max_spirit", "curr_spirit", "level", "curr_xp", "xp", "strength", "intelligence", "dexterity", "charisma", "spirit", "luck", "talent", "raceId", "cclassId", "userId" FROM "temporary_character"`);
        await queryRunner.query(`DROP TABLE "temporary_character"`);
        await queryRunner.query(`DROP TABLE "place"`);
    }

}
