import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCombat1782844471261 implements MigrationInterface {
    name = 'AddCombat1782844471261'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "combat_state" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "enemyName" varchar NOT NULL, "enemyMaxHealth" integer NOT NULL, "enemyCurrHealth" integer NOT NULL, "enemyAttack" integer NOT NULL, "enemyDefense" integer NOT NULL, "enemyXpReward" integer NOT NULL, "enemyGoldReward" integer, "status" varchar NOT NULL DEFAULT ('active'), "startedAt" datetime NOT NULL, "lastActionAt" datetime NOT NULL, "round" integer NOT NULL, "combatLog" text, "platform" varchar, "platformId" varchar, "characterId" integer)`);
        await queryRunner.query(`CREATE TABLE "temporary_travel_state" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "startedAt" datetime NOT NULL, "startX" integer NOT NULL, "startY" integer NOT NULL, "estimatedArrival" datetime NOT NULL, "totalDistance" float NOT NULL, "speed" float NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), "characterId" integer, "destinationId" integer, "platform" varchar, "platformId" varchar, CONSTRAINT "REL_77461934730bcd54c4cc3a911f" UNIQUE ("characterId"), CONSTRAINT "FK_7c0d40ff8c391c0b1b08ce986a3" FOREIGN KEY ("destinationId") REFERENCES "place" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_77461934730bcd54c4cc3a911fc" FOREIGN KEY ("characterId") REFERENCES "character" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_travel_state"("id", "startedAt", "startX", "startY", "estimatedArrival", "totalDistance", "speed", "isActive", "characterId", "destinationId") SELECT "id", "startedAt", "startX", "startY", "estimatedArrival", "totalDistance", "speed", "isActive", "characterId", "destinationId" FROM "travel_state"`);
        await queryRunner.query(`DROP TABLE "travel_state"`);
        await queryRunner.query(`ALTER TABLE "temporary_travel_state" RENAME TO "travel_state"`);
        await queryRunner.query(`CREATE TABLE "temporary_combat_state" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "enemyName" varchar NOT NULL, "enemyMaxHealth" integer NOT NULL, "enemyCurrHealth" integer NOT NULL, "enemyAttack" integer NOT NULL, "enemyDefense" integer NOT NULL, "enemyXpReward" integer NOT NULL, "enemyGoldReward" integer, "status" varchar NOT NULL DEFAULT ('active'), "startedAt" datetime NOT NULL, "lastActionAt" datetime NOT NULL, "round" integer NOT NULL, "combatLog" text, "platform" varchar, "platformId" varchar, "characterId" integer, CONSTRAINT "FK_e761519cf6c8cc9d749f40f3c4b" FOREIGN KEY ("characterId") REFERENCES "character" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_combat_state"("id", "enemyName", "enemyMaxHealth", "enemyCurrHealth", "enemyAttack", "enemyDefense", "enemyXpReward", "enemyGoldReward", "status", "startedAt", "lastActionAt", "round", "combatLog", "platform", "platformId", "characterId") SELECT "id", "enemyName", "enemyMaxHealth", "enemyCurrHealth", "enemyAttack", "enemyDefense", "enemyXpReward", "enemyGoldReward", "status", "startedAt", "lastActionAt", "round", "combatLog", "platform", "platformId", "characterId" FROM "combat_state"`);
        await queryRunner.query(`DROP TABLE "combat_state"`);
        await queryRunner.query(`ALTER TABLE "temporary_combat_state" RENAME TO "combat_state"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "combat_state" RENAME TO "temporary_combat_state"`);
        await queryRunner.query(`CREATE TABLE "combat_state" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "enemyName" varchar NOT NULL, "enemyMaxHealth" integer NOT NULL, "enemyCurrHealth" integer NOT NULL, "enemyAttack" integer NOT NULL, "enemyDefense" integer NOT NULL, "enemyXpReward" integer NOT NULL, "enemyGoldReward" integer, "status" varchar NOT NULL DEFAULT ('active'), "startedAt" datetime NOT NULL, "lastActionAt" datetime NOT NULL, "round" integer NOT NULL, "combatLog" text, "platform" varchar, "platformId" varchar, "characterId" integer)`);
        await queryRunner.query(`INSERT INTO "combat_state"("id", "enemyName", "enemyMaxHealth", "enemyCurrHealth", "enemyAttack", "enemyDefense", "enemyXpReward", "enemyGoldReward", "status", "startedAt", "lastActionAt", "round", "combatLog", "platform", "platformId", "characterId") SELECT "id", "enemyName", "enemyMaxHealth", "enemyCurrHealth", "enemyAttack", "enemyDefense", "enemyXpReward", "enemyGoldReward", "status", "startedAt", "lastActionAt", "round", "combatLog", "platform", "platformId", "characterId" FROM "temporary_combat_state"`);
        await queryRunner.query(`DROP TABLE "temporary_combat_state"`);
        await queryRunner.query(`ALTER TABLE "travel_state" RENAME TO "temporary_travel_state"`);
        await queryRunner.query(`CREATE TABLE "travel_state" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "startedAt" datetime NOT NULL, "startX" integer NOT NULL, "startY" integer NOT NULL, "estimatedArrival" datetime NOT NULL, "totalDistance" float NOT NULL, "speed" float NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), "characterId" integer, "destinationId" integer, CONSTRAINT "REL_77461934730bcd54c4cc3a911f" UNIQUE ("characterId"), CONSTRAINT "FK_7c0d40ff8c391c0b1b08ce986a3" FOREIGN KEY ("destinationId") REFERENCES "place" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_77461934730bcd54c4cc3a911fc" FOREIGN KEY ("characterId") REFERENCES "character" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "travel_state"("id", "startedAt", "startX", "startY", "estimatedArrival", "totalDistance", "speed", "isActive", "characterId", "destinationId") SELECT "id", "startedAt", "startX", "startY", "estimatedArrival", "totalDistance", "speed", "isActive", "characterId", "destinationId" FROM "temporary_travel_state"`);
        await queryRunner.query(`DROP TABLE "temporary_travel_state"`);
        await queryRunner.query(`DROP TABLE "combat_state"`);
    }

}
